### ISSUE TITLE
1.1.4 issue

### ISSUE THREAD

**Issue by saldous** [SvenTiigi/WhatsNewKit#13]
after updating to 1.1.4, getting crash:

```
dyld: Symbol not found: _$S11WhatsNewKit08KeyValueaB12VersionStoreCAA08ReadableabfG0AAWP
  Referenced from: /Users/me/Library/Developer/CoreSimulator/Devices/F61169B1-9C1F-4301-9DF6-BDB79FA902A0/data/Containers/Bundle/Application/D9BF5E1D-67E3-46EC-8D5C-F6E6573374DD/MyApp.app/MyApp
  Expected in: /Users/me/Library/Developer/CoreSimulator/Devices/F61169B1-9C1F-4301-9DF6-BDB79FA902A0/data/Containers/Bundle/Application/D9BF5E1D-67E3-46EC-8D5C-F6E6573374DD/MyApp.app/Frameworks/WhatsNewKit.framework/WhatsNewKit
 in /Users/me/Library/Developer/CoreSimulator/Devices/F61169B1-9C1F-4301-9DF6-BDB79FA902A0/data/Containers/Bundle/Application/D9BF5E1D-67E3-46EC-8D5C-F6E6573374DD/MyApp.app/MyApp
(lldb) 
```

**Comment by saldous** [comment]
cleaned build folder and seems the error went away.
